# Generated by Django 4.2.6 on 2023-11-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_url",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publication_year",
        ),
        migrations.RemoveField(
            model_name="book",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="book",
            name="summary",
        ),
        migrations.AddField(
            model_name="book",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
