# Generated by Django 4.2.5 on 2023-11-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookstore",
            "0002_remove_book_cover_url_remove_book_publication_year_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
