# Generated by Django 4.2.5 on 2023-12-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0003_book_isbn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
